import {
  Rocket,
  Zap,
  Star,
  Check,
  ArrowRight,
  User,
  Users,
  Settings,
  Shield,
  Lock,
  Heart,
  Sparkles,
  TrendingUp,
  Target,
  Award,
  Gift,
  Clock,
  Calendar,
  Mail,
  Phone,
  Globe,
  MapPin,
  Link,
  Code,
  Database,
  Server,
  Cloud,
  Download,
  Upload,
  Search,
  Filter,
  Layers,
  Layout,
  Grid,
  List,
  Image,
  Video,
  Music,
  File,
  Folder,
  Edit,
  Trash,
  Plus,
  Minus,
  X,
  Menu,
  Home,
  Play,
  Send,
  MessageCircle,
  Briefcase,
  BarChart,
  PieChart,
  Cpu,
  Smartphone,
  Key,
  Eye,
  UserPlus,
  UserCheck,
  HelpCircle,
  Info,
  AlertCircle,
  CheckCircle,
  XCircle,
  Copy,
  Bookmark,
  Share,
  ExternalLink,
  RefreshCw,
  RotateCw,
  Maximize,
  Minimize,
  ChevronRight,
  ChevronDown,
  ArrowUp,
  ArrowDown,
  type LucideIcon,
} from "lucide-react";

// Icon registry with all available icons
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  rocket: Rocket,
  zap: Zap,
  star: Star,
  check: Check,
  "arrow-right": ArrowRight,
  user: User,
  users: Users,
  settings: Settings,
  shield: Shield,
  lock: Lock,
  heart: Heart,
  sparkles: Sparkles,
  "trending-up": TrendingUp,
  target: Target,
  award: Award,
  gift: Gift,
  clock: Clock,
  calendar: Calendar,
  mail: Mail,
  phone: Phone,
  globe: Globe,
  "map-pin": MapPin,
  link: Link,
  code: Code,
  database: Database,
  server: Server,
  cloud: Cloud,
  download: Download,
  upload: Upload,
  search: Search,
  filter: Filter,
  layers: Layers,
  layout: Layout,
  grid: Grid,
  list: List,
  image: Image,
  video: Video,
  music: Music,
  file: File,
  folder: Folder,
  edit: Edit,
  trash: Trash,
  plus: Plus,
  minus: Minus,
  x: X,
  menu: Menu,
  home: Home,
  play: Play,
  send: Send,
  "message-circle": MessageCircle,
  briefcase: Briefcase,
  "bar-chart": BarChart,
  "pie-chart": PieChart,
  cpu: Cpu,
  smartphone: Smartphone,
  key: Key,
  eye: Eye,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  "help-circle": HelpCircle,
  info: Info,
  "alert-circle": AlertCircle,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  copy: Copy,
  bookmark: Bookmark,
  share: Share,
  "external-link": ExternalLink,
  "refresh-cw": RefreshCw,
  "rotate-cw": RotateCw,
  maximize: Maximize,
  minimize: Minimize,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
};

// Organized by category for the icon picker
export const ICON_CATEGORIES = {
  actions: [
    "rocket",
    "zap",
    "play",
    "send",
    "download",
    "upload",
    "refresh-cw",
    "rotate-cw",
    "share",
    "external-link",
  ],
  communication: [
    "mail",
    "phone",
    "message-circle",
    "globe",
    "video",
  ],
  business: [
    "briefcase",
    "trending-up",
    "bar-chart",
    "pie-chart",
    "target",
    "award",
    "gift",
  ],
  technology: [
    "code",
    "database",
    "server",
    "cloud",
    "cpu",
    "smartphone",
    "settings",
  ],
  security: [
    "shield",
    "lock",
    "key",
    "eye",
    "check-circle",
  ],
  users: [
    "user",
    "users",
    "user-plus",
    "user-check",
  ],
  navigation: [
    "home",
    "menu",
    "search",
    "filter",
    "arrow-right",
    "arrow-up",
    "arrow-down",
    "chevron-right",
    "chevron-down",
    "external-link",
  ],
  status: [
    "check",
    "x",
    "alert-circle",
    "info",
    "help-circle",
    "check-circle",
    "x-circle",
  ],
  objects: [
    "star",
    "heart",
    "sparkles",
    "clock",
    "calendar",
    "map-pin",
    "link",
    "bookmark",
  ],
  editing: [
    "edit",
    "trash",
    "copy",
    "plus",
    "minus",
    "maximize",
    "minimize",
  ],
  media: [
    "image",
    "video",
    "music",
    "file",
    "folder",
    "layers",
    "layout",
    "grid",
    "list",
  ],
};

// Get all icon names as a flat array
export const ALL_ICONS = Object.keys(ICON_REGISTRY);

// Get icon component by name
export function getIconComponent(name: string): LucideIcon | null {
  return ICON_REGISTRY[name] || null;
}

// Check if a string is a valid icon name
export function isValidIcon(name: string): boolean {
  return name in ICON_REGISTRY;
}
